### ISSUE TITLE
feature request for real time update

### ISSUE THREAD

**Issue by FrankBuss** [bokontep/BokontepByteBeatMachine#1]
I cloned your project:
https://github.com/FrankBuss/Formula
Maybe interesting for your project as well: see the last commit, where a text change automatically parses the formula again. No need for a manual Initialize.

**Comment by FrankBuss** [comment]
Not the last commit anymore, this is the diff:
https://github.com/FrankBuss/Formula/commit/395c73848fafe4fa8a78b9fb579787b233e8058a
Pretty simple.

**Comment by bokontep** [comment]
After almost a year I managed to integrate the requested functionality. Thanks for the suggestion!
